python3-flit_core
python3-installer
python3-wheel
python3-pyproject-hooks
python3-build
python3-cssselect
python3-webencodings
html5lib
python3-typing-extensions
python3-packaging-opt
python3-setuptools-opt
python3-calver
python3-trove-classifiers
python-zipp
python-importlib_metadata
python3-setuptools-scm-opt
python3-pluggy
python3-pathspec
python3-editables
python3-hatchling
python3-soupsieve
BeautifulSoup4
python3-lxml
python3-dateutil
OWSLib
