OpenBLAS
doctest
xsimd
python3-flit_core
python3-installer
python3-wheel
python3-pyproject-hooks
python3-build
python3-packaging-opt
python3-setuptools-opt
# python3-meson-opt
python3-pyproject-metadata
python3-mesonpy
python3-cython-opt
python3-numpy
python3-gast
python3-beniget
python3-pythran
python3-typing-extensions
python3-flit_scm
python3-exceptiongroup
python3-calver
python3-trove-classifiers
python-zipp
python-importlib_metadata
python3-setuptools-scm-opt
python3-pluggy
python3-pathspec
python3-editables
python3-hatchling
python3-hatch_vcs
python3-scikit-build-core
pybind11
python3-scipy
