python3-flit_core
python3-installer
python3-wheel
python3-pyproject-hooks
python3-build
python3-packaging-opt
python3-setuptools-opt
python-zipp
python-importlib_metadata
python3-typing-extensions
python3-setuptools-scm-opt
python3-flit_scm
python3-exceptiongroup
python3-calver
python3-trove-classifiers
python3-pluggy
python3-pathspec
python3-editables
python3-hatchling
python3-hatch_vcs
python3-scikit-build-core
pybind11
python3-toml
importlib-resources
python3-meson-opt
python3-pyproject-metadata
python3-mesonpy
python3-cython-opt
python3-numpy
cppy
python3-kiwisolver
python3-pkgconfig
python3-iniconfig
python3-pytest
python3-pytest-runner
python3-filelock
python3-platformdirs
python3-discovery
python3-distlib
python3-virtualenv
python3-pyproject-api
colorama
python3-cachetools
python3-tox
python3-lz4
python3-cssselect
python3-webencodings
html5lib
python3-soupsieve
BeautifulSoup4
python3-lxml
python3-uharfbuzz
python3-fs
python3-zopfli
OpenBLAS
doctest
xsimd
python3-gast
python3-beniget
python3-pythran
python3-scipy
python-unicodedata2
python3-fonttools
python3-dateutil
python3-cycler
python3-contourpy
python3-matplotlib
