python3-flit_core
python3-installer
python3-wheel
python3-pyproject-hooks
python3-build
python3-packaging-opt
python3-setuptools-opt
python3-typing-extensions
python3-attrdict
python3-pathlib2
nanosvg
unifdef
python3-meson-opt
libsoup3
xdg-dbus-proxy
libwpe
wpebackend-fdo
geoclue2
bubblewrap
webkit2gtk4.1
wxWidgets
wxPython4
